name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install huggingface_hub
          python -c "from huggingface_hub import HfApi; HfApi().upload_folder(folder_path='.', repo_id='N220343nagaraju/aquatrace-backend', repo_type='space', ignore_patterns=['.git/*', '.github/*'], delete_patterns='*')"
